Starting on : Fri Aug  1 16:16:35 EDT 2014
Starting on : Fri Aug  1 16:16:35 EDT 2014
Starting on : Fri Aug  1 16:16:35 EDT 2014
Running on node : v7-hb4.titan
Running on node : v7-hb4.titan
Running on node : v7-hb4.titan
Current directory : /ifs/scratch/pimri/soccog/scripts/mastersort/scripts_dir
Current job ID : 7722001
Current job name : j7403_anat-1-1
Current directory : /ifs/scratch/pimri/soccog/scripts/mastersort/scripts_dir
Current job ID : 7721890
Current job name : j7403_anat-1-1
Current directory : /ifs/scratch/pimri/soccog/scripts/mastersort/scripts_dir
Current job ID : 7723589
Current job name : j7403_anat-1-1
Starting on : Fri Aug  1 16:16:35 EDT 2014
Running on node : v7-hb4.titan
Current directory : /ifs/scratch/pimri/soccog/scripts/mastersort/scripts_dir
Current job ID : 7721891
Current job name : j7403_anat-1-1
Unable to run job: job rejected: no script in your request.
Exiting.
['7403', 'anat-1-1']
Traceback (most recent call last):
  File "/ifs/scratch/pimri/soccog/scripts/mastersort/scripts_dir/p7403_anat-1-1.py", line 14, in <module>
    qsub_cnv_out = dcm_ops.cnv_dcm('/ifs/scratch/pimri/soccog/test_working/7403/anat-1-1', '7403_anat-1-1', '/ifs/scratch/pimri/soccog/scripts/mastersort/scripts_dir/cnv')
  File "/ifs/scratch/pimri/soccog/scripts/mastersort/scripts_dir/dcm_ops.py", line 120, in cnv_dcm
    shell=True)
  File "/ifs/scratch/pimri/soccog/scripts/mastersort/scripts_dir/uf.py", line 64, in check_output
    raise error
subprocess.CalledProcessError: Command 'qsub qsub_7403_anat-1-1.sh' returned non-zero exit status 1
['7403', 'anat-1-1']
Traceback (most recent call last):
  File "/ifs/scratch/pimri/soccog/scripts/mastersort/scripts_dir/p7403_anat-1-1.py", line 13, in <module>
    os.rename(old, new)
OSError: [Errno 2] No such file or directory
['7403', 'anat-1-1']
Traceback (most recent call last):
  File "/ifs/scratch/pimri/soccog/scripts/mastersort/scripts_dir/p7403_anat-1-1.py", line 13, in <module>
    os.rename(old, new)
OSError: [Errno 2] No such file or directory
Unable to run job: job rejected: no script in your request.
Exiting.
['7403', 'anat-1-1']
Traceback (most recent call last):
  File "/ifs/scratch/pimri/soccog/scripts/mastersort/scripts_dir/p7403_anat-1-1.py", line 14, in <module>
    qsub_cnv_out = dcm_ops.cnv_dcm('/ifs/scratch/pimri/soccog/test_working/7403/anat-1-1', '7403_anat-1-1', '/ifs/scratch/pimri/soccog/scripts/mastersort/scripts_dir/cnv')
  File "/ifs/scratch/pimri/soccog/scripts/mastersort/scripts_dir/dcm_ops.py", line 120, in cnv_dcm
    shell=True)
  File "/ifs/scratch/pimri/soccog/scripts/mastersort/scripts_dir/uf.py", line 64, in check_output
    raise error
subprocess.CalledProcessError: Command 'qsub qsub_7403_anat-1-1.sh' returned non-zero exit status 1
